[package]
name = "day40"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-iam = "0.1"
tokio = { version = "1", features = ["full"] }