[package]
name = "day21b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = { version = "5.1.0" }
notify-debouncer-mini = { version = "0.2.0" }
